const data = [
  {
    type: "input",
    inputType: "text",
    label: "Candidate Name",
    required: true,
    placeholder: "Enter the Candidate Name",
  },
  {
    type: "input",
    inputType: "text",
    label: "Candidate Phone",
    required: true,
    placeholder: "Enter the Candidate Phone",
  },
  {
    type: "input",
    inputType: "text",
    label: "Candidate Email",
    required: true,
    placeholder: "Enter the Candidate Email",
  },
  {
    type: "input",
    inputType: "text",
    label: "HR Responsible",
    required: true,
    placeholder: "",
  },
  {
    type: "select",
    label: "Branch",
    required: true,
    options: ["Select Branch", "Bangalore", "Coimbatore"],
  },
  {
    type: "select",
    label: "Requirement Type",
    required: true,
    options: ["Select Requirement Type", "Permanent", "Temporary"],
  },
  {
    type: "select",
    label: "Applicant Type",
    required: true,
    options: ["Select Applicant Type", "Fresher", "Experienced"],
  },
  {
    type: "select",
    label: "Requirement Base",
    required: true,
    options: ["Select Requirement Base", "Ruby on Rails", "React JS"],
  },
  {
    type: "input",
    inputType: "text",
    label: "Experience in",
    required: true,
    placeholder: "Enter Experience(Years)",
  },
  {
    type: "input",
    inputType: "text",
    label: "C - CTC(LPA)",
    required: false,
    placeholder: "Enter the C-CTC",
  },
  {
    type: "input",
    inputType: "text",
    label: "E - CTC(LPA)",
    required: false,
    placeholder: "Enter the E-CTC",
  },
  {
    type: "input",
    inputType: "text",
    label: "Notice Period(days)",
    required: false,
    placeholder: "Enter the number of days",
  },
  {
    type: "input",
    inputType: "text",
    label: "Working/Last Company",
    required: false,
    placeholder: "Enter the Working/Last Company",
  },
  {
    type: "input",
    inputType: "text",
    label: "Location",
    required: true,
    placeholder: "Enter the Location",
  },
  {
    type: "input",
    inputType: "file",
    label: "Resume",
    required: false,
  },
  {
    type: "select",
    label: "Interview Status",
    required: false,
    options: [
      "Select the Interview Status",
      "Offered",
      "In progress",
      "Selected",
      "Rejected",
    ],
  },
  {
    type: "textarea",
    label: "Comments",
    required: false,
  },
];

export default data;
